# SSL certificates for development
# $ mkcert sasha-khandus.local www.sasha-khandus.local sasha-khandus-add.local www.sasha-khandus-add.local
#
# DEVELOPMENT:
# $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d
#
# PRODUCTION:
# $ docker-compose up -d
#
# MacOS (development only)
# docker-sync-stack start
version: '3.7'
services:
  php-apache:
    container_name: sasha-khandus.local
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        # needed for the build stage
        # Install memcached inside container if needed. Better to use external Memcached container and only have
        # php extension to connect to it
        - MEMCACHED=0
    restart: always
    labels:
      # - traefik.enable=false
      - traefik.http.frontend.rule=Host:sasha-khandus.local,www.sasha-khandus.local,sasha-khandus-add.local,www.sasha-khandus-add.local
      - traefik.http.frontend.entryPoints=http
      - traefik.https.frontend.rule=Host:sasha-khandus.local,www.sasha-khandus.local,sasha-khandus-add.local,www.sasha-khandus-add.local
      - traefik.https.frontend.entryPoints=https
      - traefik.https.protocol=https
      - traefik.https.port=443
    # Must add extra_hosts to be written to /etc/hosts - otherwise containerized application can not curl itself
    extra_hosts:
      - "sasha-khandus.local www.sasha-khandus.local sasha-khandus-add.local www.sasha-khandus-add.local:127.0.0.1"
#    links:
#      - memcached
    links:
      - redis
    external_links:
      - mysql57:mysql
#    networks:
#      - reverse-proxy
    network_mode: bridge
    volumes:
      - .:/var/www/html
      - /misc/share/ssl:/certs
      - ./docker/virtual-host.conf:/etc/apache2/sites-enabled/virtual-host.conf

  redis:
    image: redis:latest
    network_mode: bridge
    labels:
      - traefik.enable=false
    restart: always

#  memcached:
#    image: 'memcached:1.5'
#    network_mode: bridge
#    restart: always

#networks:
#  reverse-proxy:
#    external: true