<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="sashakh-chat" style="display: none;">
    <h3><?= $block->escapeHtml(__('Chat')) ?></h3>
    <div id="sashakh-chat-list"></div>
    <button type="button"
            class="button"
            id="sashakh-chat-edit-button"
            data-mage-init='{"sashakh_chat_button": {}}'
    ><?= $block->escapeHtml(__('Edit Chat')) ?></button>
</div>