<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div data-bind="scope: 'chatForm'" style="width: 50%; margin: 0 auto">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "chatForm": {
                        "component": "sashakh_chat_form"
                    }
                }
            }
        }
    }
</script>