<?php /** @var \Sashakh\Chat\Block\Messages $block */
$messagesCollection = $block->getAllMessages();
$messages = array_reverse($messagesCollection->getItems());
?>
    <ul class="messages-list">
        <?php /** @var \Sashakh\Chat\Model\Chat $message */
            foreach ($messages as $message):
                $authorType = $message->getAuthorType() === 1 ? 'user' : 'admin';
        ?>
                <li class="chat-message <?= $block->escapeHtml($authorType) ?>">
                    <p class='message-date'><?= $block->escapeHtml($message->getCreatedAt()) ?></p>
                    <p class='message-name'><?= $block->escapeHtml($message->getAuthorName()) ?></p>
                    <p class='message-message'><?= $block->escapeHtml($message->getMessage()) ?></p>
                </li>
        <?php endforeach; ?>
    </ul>
