<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="sashakh-chat-block"
     data-mage-init='{"sashakh_chat_openButton": {}}'
>
    <a href="javascript:void(0);"
       class="sashakh-chat-open-button active"
       id="sashakh-chat-open-button"
    ></a>
    <button type="button"
            class="sashakh-chat-destroy-button"
            id="sashakh-chat-destroy-button"
    ><?= $block->escapeHtml('X') ?></button>
</div>