<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="sashakh-chat-sidebar"
     style="display: none;"
     data-mage-init='{"sashakh_chat_sidebar": {}}'
>
    <h3><?= $block->escapeHtml(__('Chat')) ?></h3>
    <div id="sashakh-chat-list"></div>
    <textarea id="sashakh-chat-textarea"></textarea>
    <button type="button"
            class="action primary"
            id="sashakh-chat-edit-button"
    ><?= $block->escapeHtml(__('Edit Chat')) ?></button>
    <button type="button"
            id="sashakh-chat-close-sidebar-button"
    ><?= $block->escapeHtml(__('Close')) ?></button>
</div>